### ISSUE TITLE
Is this code complete??

### ISSUE THREAD

**Issue by ignabelitzky** [Baanista/SpaceParticleSimulator#8]
I try to execute it, and didn't succed.
After a while I mange to "execute it" but I get segmentation fault.
My next attempt was to refactor the code, I manage to do that barely.
But I encounter so many errors that I'm giving up on this.

I didn't get near the video and images that you show in the  README.

If anyone want to see the refactorize code is here: https://github.com/ignabelitzky/SpaceParticleSimulator

Please response through here if we can colaborate together to get this code to work.
Cheers and sorry about my english, it's not my first language :/

**Comment by Baanista** [comment]
Yea let me try to fix the problem. I have not worked on this project for a while. I might have pushed a version with errors. Right now I am working on adding neural networks.

**Comment by ignabelitzky** [comment]
Ok, glad you are still active on this project.
